# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Gen TeaFile

on:
  workflow_dispatch: "Gen-File"
  schedule:
    - cron:  '* */6 * * *'
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # 使用别人封装好的的action，用于clone该仓库的源码到工作流中
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f tencentdoc/requirements.txt ]; then pip install -r tencentdoc/requirements.txt; fi
    - name: 'Gen File'
      run: python tencentdoc/excel.py
      
    - name: Add Diff
      run: git add .

    - name: Commit files
      run: |
          git config --local user.email "745268436@qq.com"
          git config --local user.name "wangzhang"
          git commit -m "🐻[Auto] fetch teaFile" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token:  ${{secrets.TOKEN}}
        branch: main

